
name: Build and Push MERN Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest


  deploy-to-k3s:
    name: Deploy to K3s
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Update backend image
        run: |
          kubectl set image deployment/backendmainn \
            ecommerce-backend=${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest \
            -n emain

      - name: Update frontend image
        run: |
          kubectl set image deployment/frontendmainn \
            ecommerce-frontend=${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest \
            -n emain

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/backendmainn -n emain --timeout=180s
          kubectl rollout status deployment/frontendmainn -n emain --timeout=180s
